### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'instance')

### ISSUE THREAD

**Issue by krisztian-fekete** [sendinblue/APIv3-nodejs-library#116] opened 2022-02-25 18:15 UTC
Trying to add this with webpack to my project. Followed the installation instructions in the readme, added 
```
parser: {
    amd: false
}
```      
to my `webpack.config.js`. Created a js file and added 

```
const SibApiV3Sdk = require('sib-api-v3-sdk');
let defaultClient = SibApiV3Sdk.ApiClient.instance;
```
Build finishes without errors, but I get `Uncaught TypeError: Cannot read properties of undefined (reading 'instance') when loading this file on a page.

**Comment by krisztian-fekete** [comment] 2022-03-02 09:31
Might be a duplicate of https://github.com/sendinblue/APIv3-nodejs-library/issues/101

**Comment by shubhamUpadhyayInBlue** [comment] 2022-04-04 07:05
Hi @krisztian-fekete
Yes, it is a duplicate of #101. So, I am closing this one.

**Closed by shubhamUpadhyayInBlue** 2022-04-04 07:05 UTC

**Comment by bcwin-i** [comment] 2022-11-19 13:36
Hi everyone, I was able to resolve this issue by changing the import. See changes below.
`import SibApiV3Sdk from '@sendinblue/client'` to `import * as SibApiV3Sdk from '@sendinblue/client'`
